// Author: Robert Davis

#include "gmml/internal/coordinate_file.h"

#include <algorithm>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <stdexcept>
#include <vector>

#include "gmml/internal/environment.h"
#include "gmml/internal/geometry.h"
#include "utilities.h"

using std::string;
using std::vector;

namespace gmml {

const char *CoordinateFile::kDefaultTitle =
        "GENERATED BY GMML (http://code.google.com/p/gmml)";

struct CoordinateFile::Impl {
    Impl() : title_(kDefaultTitle), noncoordinate_count_(0) {}

    ~Impl() {
        cleanup();
    }

    void cleanup() {
        std::for_each(coordinates_.begin(), coordinates_.end(), DeletePtr());
    }

    void read(const string& file_name);
    void read(std::istream& in);
    bool process_coordinate_line(const string& line);
    Coordinate *parse_coordinate(const string& str);

    void bad_file(const std::string& error) {
        cleanup();
        throw std::invalid_argument(error);
    }

    void write_coordinate(std::ostream& out,
                          const Coordinate& coordinate) const;
    void write_component(std::ostream& out, double component) const;

    string title_;
    vector<Coordinate*> coordinates_;
    int noncoordinate_count_;
};

CoordinateFile::CoordinateFile() : impl_(new Impl) {
}

CoordinateFile::CoordinateFile(const string& file_name) : impl_(new Impl) {
    impl_->read(file_name);
}

CoordinateFile::~CoordinateFile() {
}

void CoordinateFile::print(const string& file_name) const {
    std::ofstream out;
    out.open(file_name.c_str());
    write(out);
}

void CoordinateFile::print() const {
    write(std::cout);
}

void CoordinateFile::write(std::ostream& out) const {
    out << impl_->title_ << std::endl;
    int size = impl_->coordinates_.size();
    out << std::setw(kCountLabelWidth) <<
           size - impl_->noncoordinate_count_ << std::endl;
    bool odd = size & 1;
    for (int i = 0; i < size - (odd == true); i += 2) {
        impl_->write_coordinate(out, *impl_->coordinates_[i]);
        impl_->write_coordinate(out, *impl_->coordinates_[i + 1]);
        out << std::endl;
    }
    if (odd) {
        impl_->write_coordinate(out, *impl_->coordinates_[size - 1]);
        out << std::endl;
    }
}

size_t CoordinateFile::size() const {
    return impl_->coordinates_.size();
}

int CoordinateFile::noncoordinate_count() const {
    return impl_->noncoordinate_count_;
}

const Coordinate& CoordinateFile::operator[](int index) const {
    if (0 <= index && index < size())
        return *impl_->coordinates_[index];
    string error = make_string() << "Invalid coordinate index: " <<
                                    index << ".";
    throw std::range_error(error);
}

void CoordinateFile::add_coordinate(const Coordinate& coordinate) {
    impl_->coordinates_.push_back(new Coordinate(coordinate));
}

void CoordinateFile::add_noncoordinate(double x, double y, double z) {
    impl_->coordinates_.push_back(new Coordinate(x, y, z));
    impl_->noncoordinate_count_++;
}


void CoordinateFile::Impl::read(const string& file_name) {
    std::ifstream stream(find_file(file_name).c_str());
    read(stream);
}

void CoordinateFile::Impl::read(std::istream& in) {
    string line;

    if (!getline(in, line)) {
        bad_file("Invalid coordinate file.");
    }
    trim(line);
    title_ = line;

    if (!getline(in, line)) {
        bad_file("Invalid coordinate file.");
    }
    int count_label = convert_string<int>(line);

    int line_index = 2;
    while (line_index++, getline(in, line)) {
        if (!process_coordinate_line(line)) {
            bad_file(make_string() << "Error on line " << line_index << ".");
        }
    }

    noncoordinate_count_ = coordinates_.size() - count_label;
}

bool CoordinateFile::Impl::process_coordinate_line(const string& line) {
    int coords_on_line = line.size()/kCoordinateWidth/3;
    for (int i = 0; i < coords_on_line; i++) {
        string crd = line.substr(i*kCoordinateWidth*3, kCoordinateWidth*3);
        try {
            Coordinate *coordinate = parse_coordinate(crd);
            coordinates_.push_back(coordinate);
        } catch (const ConversionException& e) {
            return false;
        }
    }
    return true;
}

Coordinate *CoordinateFile::Impl::parse_coordinate(const string& str) {
    double x = convert_string<double>(str.substr(0, kCoordinateWidth));
    double y = convert_string<double>(str.substr(kCoordinateWidth,
                                                 kCoordinateWidth));
    double z = convert_string<double>(str.substr(2*kCoordinateWidth,
                                                 kCoordinateWidth));
    return new Coordinate(x, y, z);
}

void CoordinateFile::Impl::write_coordinate(
        std::ostream& out, const Coordinate& coordinate) const {
    write_component(out, coordinate.x);
    write_component(out, coordinate.y);
    write_component(out, coordinate.z);
}

void CoordinateFile::Impl::write_component(std::ostream& out,
                                           double component) const {
    out << std::setw(kCoordinateWidth) <<
           std::setprecision(kCoordinatePrecision) <<
           std::fixed <<
           component;
}

}  // namespace gmml
